services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $plentaTooltipSizes: '%plenta_tooltip.tooltip_sizes%'

    Plenta\TooltipBundle\:
        resource: ../../
        exclude: ../../{Entity,Migrations,Model,Resources,Tests,Widget}