services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Plenta\TooltipBundle\:
        resource: ../../
        exclude: ../../{Entity,Migrations,Model,Resources,Tests,Widget}